"""empty message

Revision ID: 00a569d7c4c2
Revises: f500960aeb42
Create Date: 2020-11-13 01:58:10.278101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a569d7c4c2'
down_revision = 'f500960aeb42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unknown', sa.Column('localization', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unknown', 'localization')
    # ### end Alembic commands ###
