"""empty message

Revision ID: 05ba445f9462
Revises: 00a569d7c4c2
Create Date: 2020-11-19 14:12:02.448304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ba445f9462'
down_revision = '00a569d7c4c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unknown', sa.Column('finished', sa.Boolean(), nullable=True, create_constraint=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unknown', 'finished')
    # ### end Alembic commands ###
