"""empty message

Revision ID: 081ee0d48f20
Revises: 81721f09e909
Create Date: 2020-12-16 17:36:00.853055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081ee0d48f20'
down_revision = '81721f09e909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('nonevidenced')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonevidenced',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('inv_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['inv_id'], ['stocktaking.id'], name='nonevidenced_inv_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['items_list.id'], name='nonevidenced_item_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='nonevidenced_pkey')
    )
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
