"""empty message

Revision ID: 1ae6152897ce
Revises: 05ba445f9462
Create Date: 2020-11-19 14:17:45.659910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae6152897ce'
down_revision = '05ba445f9462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('finished', sa.Boolean(), nullable=True, create_constraint=False))
    op.drop_column('unknown', 'finished')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unknown', sa.Column('finished', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('schedule', 'finished')
    # ### end Alembic commands ###
