"""empty message

Revision ID: 33a8599b4bb8
Revises: 1ae6152897ce
Create Date: 2020-11-19 15:45:10.919845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a8599b4bb8'
down_revision = '1ae6152897ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('inv_id', sa.Integer(), nullable=True))
    op.drop_constraint('schedule_item_id_fkey', 'schedule', type_='foreignkey')
    op.create_foreign_key(None, 'schedule', 'stocktaking', ['inv_id'], ['id'])
    op.drop_column('schedule', 'item_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.create_foreign_key('schedule_item_id_fkey', 'schedule', 'stocktaking', ['item_id'], ['id'])
    op.drop_column('schedule', 'inv_id')
    # ### end Alembic commands ###
