"""empty message

Revision ID: 4c3938f92bb4
Revises: e8a25e209892
Create Date: 2021-01-09 13:23:03.316186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c3938f92bb4'
down_revision = 'e8a25e209892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'deleted')
    op.add_column('evidenced', sa.Column('inv_number', sa.String(), nullable=True))
    op.drop_column('evidenced', 'deleted')
    op.add_column('users', sa.Column('otp_secret', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_secret')
    op.add_column('evidenced', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('evidenced', 'inv_number')
    op.add_column('comments', sa.Column('deleted', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
