"""empty message

Revision ID: 58dd1d23dea4
Revises: af90c6827b5f
Create Date: 2020-11-12 14:16:18.259712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58dd1d23dea4'
down_revision = 'af90c6827b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocktaking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('localization', sa.String(), nullable=True),
    sa.Column('mpk_number', sa.Integer(), nullable=True),
    sa.Column('commissioner', sa.String(), nullable=True),
    sa.Column('com_members', postgresql.ARRAY(sa.String(), dimensions=1), nullable=True),
    sa.Column('evidenced', postgresql.ARRAY(sa.Integer(), dimensions=1), nullable=True),
    sa.Column('non_evidenced', postgresql.ARRAY(sa.Integer(), dimensions=1), nullable=True),
    sa.Column('unknown', postgresql.ARRAY(sa.Integer(), dimensions=1), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True, create_constraint=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unknown',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inv_number', sa.String(), nullable=True),
    sa.Column('add_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('date_end', sa.DateTime(), nullable=True),
    sa.Column('task', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['stocktaking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    op.drop_table('unknown')
    op.drop_table('stocktaking')
    # ### end Alembic commands ###
