"""empty message

Revision ID: 81721f09e909
Revises: cf8a0cd4b639
Create Date: 2020-12-15 13:06:50.532887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81721f09e909'
down_revision = 'cf8a0cd4b639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'public_id')
    # ### end Alembic commands ###
