"""empty message

Revision ID: af90c6827b5f
Revises: ba97cf499639
Create Date: 2020-11-07 14:59:54.086963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af90c6827b5f'
down_revision = 'ba97cf499639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=True),
    sa.Column('edit_timestamp', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('items', sa.Column('index_nbr', sa.String(), nullable=True))
    op.drop_column('items', 'inv_number')
    op.add_column('items_list', sa.Column('add_date', sa.DateTime(), nullable=True))
    op.add_column('items_list', sa.Column('documents', sa.String(), nullable=True))
    op.add_column('items_list', sa.Column('img', sa.String(), nullable=True))
    op.add_column('items_list', sa.Column('inv_number', sa.String(), nullable=True))
    op.add_column('items_list', sa.Column('localization', sa.String(), nullable=True))
    op.drop_column('items_list', 'number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items_list', sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('items_list', 'localization')
    op.drop_column('items_list', 'inv_number')
    op.drop_column('items_list', 'img')
    op.drop_column('items_list', 'documents')
    op.drop_column('items_list', 'add_date')
    op.add_column('items', sa.Column('inv_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('items', 'index_nbr')
    op.drop_table('comments')
    # ### end Alembic commands ###
