"""empty message

Revision ID: c4f8b2d91290
Revises: 081ee0d48f20
Create Date: 2021-01-05 01:29:47.001941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f8b2d91290'
down_revision = '081ee0d48f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('date_exp_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'date_exp_end')
    # ### end Alembic commands ###
