"""empty message

Revision ID: cf8a0cd4b639
Revises: 70bb353abc30
Create Date: 2020-12-14 01:32:37.386443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8a0cd4b639'
down_revision = '70bb353abc30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stocktakings', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stocktakings')
    # ### end Alembic commands ###
