"""empty message

Revision ID: fc7ed2c5a64a
Revises: 33a8599b4bb8
Create Date: 2020-11-25 16:57:08.226114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc7ed2c5a64a'
down_revision = '33a8599b4bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generator')
    # ### end Alembic commands ###
